# Generated by Django 2.1.5 on 2019-01-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=45)),
                ('robot_number', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('event_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
