# Generated by Django 2.1.5 on 2019-01-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='hatches_secured',
            field=models.IntegerField(default=0),
        ),
    ]
